logsBucket: 'weblogs-pharma'
steps:
- name: 'ubuntu'
  args: ['rm', '-f', 'package-lock.json']
  dir: '.'
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: '.'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'clean-build']
  dir: '.' 
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-r', '-d', './public', 'gs://www.pharmtechsonly.com']